# Case - LLM for Translation

In [1]:
import sys
sys.path.append('C:/Users/ge28pih/PycharmProjects/ICU-Decision Making-OCRL')

In [2]:
from Data.SICdb_discharge.data_preprocess import *

In [3]:
discharge_data_preprocess = ICUDataInput(
    cases_path = 'C:/Users/ge28pih/PycharmProjects/discharge_decision_making/icu_data/salzburg/cases.csv.gz',
    d_references_path = 'C:/Users/ge28pih/PycharmProjects/discharge_decision_making/icu_data/salzburg/d_references.csv.gz',
    laboratory_path = 'C:/Users/ge28pih/PycharmProjects/discharge_decision_making/icu_data/salzburg/laboratory.csv.gz',
    medication_path = 'C:/Users/ge28pih/PycharmProjects/discharge_decision_making/icu_data/salzburg/medication.csv.gz',
    data_float_h_path = None, # it could be None, and use ChartEventsProcess to get the data
    data_range_path = 'C:/Users/ge28pih/PycharmProjects/discharge_decision_making/icu_data/salzburg/data_range.csv.gz',
    data_ref_path = 'C:/Users/ge28pih/PycharmProjects/discharge_decision_making/icu_data/salzburg/data_ref.csv.gz',
    data_compression = 'gzip'
)

In [4]:
discharge_data_preprocess.load_data()

In [5]:
discharge_data_preprocess.data_float_h_data

In [6]:
discharge_data_preprocess.d_references_data

,ReferenceGlobalID,ReferenceValue,ReferenceName,ReferenceDescription,ReferenceUnit,ReferenceOrder,ReferenceType,Data,LOINC_code,LOINC_short,LOINC_long
0,2,INIC,HospitalUnit,9 bed intermediate care ward,NaN,0,0.0,NaN,NaN,NaN,NaN
1,3,CWIN,HospitalUnit,14 bed intensive care ward,NaN,0,0.0,NaN,NaN,NaN,NaN
2,4,INBD,HospitalUnit,9 bed intensive care ward,NaN,0,0.0,NaN,NaN,NaN,NaN
3,5,INID,HospitalUnit,"9 bed mixed ward (intermediate care, non-invas...",NaN,0,0.0,NaN,NaN,NaN,NaN
4,15,MVImporter,Importer,NaN,NaN,0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1617,3141,Oxyflow Flow,SignalFloat,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1618,3142,Optiflow O2,SignalFloat,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1619,3143,Optiflow Flow,SignalFloat,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1620,3144,O2 Flow,SignalFloat,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1621,3145,CAM-ICU,Scores,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [7]:
discharge_data_preprocess.d_references_data['ReferenceUnit'].unique()

array([nan, '%', 'None', '/100Leuko', '/3/cmm', 'µg/dl', 'µg/l', 'µg/ml',
       'µmol/L', 'Cells/µL', 'fl', 'g/dl', 'g/L', 'IU/L', 'IU/ml',
       'mg/24h', 'mg/dl', 'mg/gKrea', 'mg/L', 'min', 'ml', 'ml/min',
       'mm/h', 'mmHg', 'mmol/24h', 'mmol/L', 'mmol/mol', 'mOsm/kg',
       'mU/L', 'ng/L', 'ng/ml', 'Per mill', 'pg', 'pg/ml', 'pmol/L',
       'Ratio', 'sec', 'T/L.', 'U', 'U/L', 'U/mL', 'µg/24h', '°C',
       'mmol/kg', '/min', 'mbar', 'L', 'Vol%', 'ml/h', 'g', 'mol',
       'drops', 'IE', 'bag', 'unit', 'cm', 'U/min', 'L/min', 'kcal',
       'seconds', 'g\\h', 'g\\h\\kg', 'ml/mbar'], dtype=object)

In [8]:
discharge_data_preprocess.d_references_data[discharge_data_preprocess.d_references_data['ReferenceUnit'] == '/min']

,ReferenceGlobalID,ReferenceValue,ReferenceName,ReferenceDescription,ReferenceUnit,ReferenceOrder,ReferenceType,Data,LOINC_code,LOINC_short,LOINC_long
546,707,HeartRateECG,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
547,708,HeartRateSPO2,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
558,719,RespRate,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
563,724,HeartRateABP,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
1485,2274,RespRateEKG,SignalFloat,NaN,/min,0,NaN,NaN,NaN,NaN,NaN
1491,2280,RespRateSpontanous,SignalFloat,NaN,/min,0,NaN,NaN,NaN,NaN,NaN
1493,2282,RespRate,RespiratorSetting,NaN,/min,0,NaN,NaN,NaN,NaN,NaN

In [9]:
discharge_data_preprocess.data_ref_data

            id  CaseID  FieldID  RefID
0       166070  100023     3096   2017
1       166071  100027     3096   2017
2       166072  100066     3096   2017
3       166073  100097     3096   2017
4       166074  100130     3096   2017
...        ...     ...      ...    ...
381052  801608  999934     3114   3115
381053  801609  999947     3113   3117
381054  801610  999947     3114   3115
381055  801611  999963     3113   3116
381056  801612  999963     3114   3115

[381057 rows x 4 columns]

In [10]:
# [len(discharge_data_preprocess.d_references_data['ReferenceGlobalID'].unique()), len(discharge_data_preprocess.data_float_h_data['DataID'].unique())]

In [11]:
search_variable = VariableSearch(d_items_table = discharge_data_preprocess.d_references_data, 
                                 search_column = 'ReferenceValue', 
                                 id_column = 'ReferenceGlobalID')

In [ ]:
api_key = 'xx-xxx-xxxx-xxxxxxxxx'

In [14]:
items_id_list = search_variable.search_by_keyword(keyword = 'heart', 
                                                  output_column = 'ReferenceGlobalID', 
                                                  use_regex = False, 
                                                  enable_translation = True, 
                                                  target_languages = ['German'],  
                                                  translation_service = 'claude', 
                                                  api_key = api_key, 
                                                  custom_translator = None, enable_interactive_mode = True)

Translated 'HEART' to German: 'Herz'
Translated 'heart' to German: 'Herz'
Translated 'Heart' to German: 'Herz'

🔍 Initial search found 12 results for 'heart'
✅ Found 12 results

📋 All initial search results:
  - HeartRateECG (ID: 707)
  - HeartRateSPO2 (ID: 708)
  - HeartRateABP (ID: 724)
  - HeartSurgeryType (ID: 3096)
  - Herzchirurgie (ID: 744)
  - Herzchirurgie (ID: 2208)
  - Herz: CABG (ID: 2227)
  - Herz: Klappe mit CABG (ID: 2237)
  - Herz: Klappe (ID: 2240)
  - Herz: Andere (ID: 2241)
  - Transplantation: Herz/Lunge (ID: 2270)
  - Transplantation: Herz (ID: 2272)

============================================================
🤖 ENHANCED SEARCH ASSISTANT
============================================================
I see you're looking for variables related to: 'heart'
I can help you find more relevant variables using AI analysis.

Please choose an option:
1. 📊 Analyze all available variable names for relevance
2. 🔬 Search by measurement units
3. 💬 Chat with assistant (ask questions about the search)
4. ❌ Exit enhanced search

🔬 Analyzing measurement units...

🔬 UNIT ANALYSIS RESULTS:
----------------------------------------
Based on the medical context and relevance to "heart," here are the units most likely related to cardiac measurements:

**Most Relevant Units:**

- **mmHg (Relevance: 5/5)**: Primary unit for blood pressure measurement, essential for cardiac function assessment and cardiovascular health monitoring

- **/min (Relevance: 5/5)**: Standard unit for heart rate (beats per minute), one of the most fundamental cardiac vital signs

- **mbar (Relevance: 4/5)**: Alternative pressure unit that can be used for cardiac pressure measurements, though less common than mmHg in clinical practice

- **seconds (Relevance: 4/5)**: Used for measuring cardiac intervals in ECG analysis (PR interval, QRS duration, QT interval) and cardiac cycle timing

- **sec (Relevance: 4/5)**: Abbreviated form of seconds, same application as above for cardiac timing measurements

- **ml/min (Relevance: 4/5)**: Used for cardiac output measurements and coronary blood flow assessments

- **ml (Relevance: 3/5)**: Volume measurements relevant to stroke volume, cardiac chamber volumes, and ejection fraction calculations

- **L (Relevance: 3/5)**: Larger volume unit used for cardiac output measurements (liters per minute)

- **min (Relevance: 3/5)**: Time unit used in various cardiac assessments and stress test protocols

- **cm (Relevance: 3/5)**: Used in echocardiography for measuring cardiac chamber dimensions and wall thickness

- **U/min (Relevance: 2/5)**: Could be relevant for cardiac enzyme activity measurements (like CK-MB units per minute)

These units are commonly encountered in cardiology for measuring heart function, cardiac output, blood pressure, heart rhythm, and structural cardiac parameters.

✅ Found 7 items with selected units

🎉 FINAL RESULTS: 16 items total
   📊 Initial search: 12 items
   🆕 New items added: 4 items
   📈 Enhancement rate: 4/12 = 33.3%

📋 Complete final results list:
  ✅ Herzchirurgie (ID: 2208) [Initial]
  ✅ Herz: Klappe (ID: 2240) [Initial]
  ✅ Herz: Andere (ID: 2241) [Initial]
  ✅ HeartRateECG (ID: 707) [Initial]
  ✅ HeartRateSPO2 (ID: 708) [Initial]
  ✅ Transplantation: Herz (ID: 2272) [Initial]
  🆕 (ID: 2274) [New - Enhanced Search]
  ✅ Herzchirurgie (ID: 744) [Initial]
  🆕 (ID: 2280) [New - Enhanced Search]
  🆕 (ID: 2282) [New - Enhanced Search]
  🆕 (ID: 719) [New - Enhanced Search]
  ✅ Herz: CABG (ID: 2227) [Initial]
  ✅ HeartRateABP (ID: 724) [Initial]
  ✅ HeartSurgeryType (ID: 3096) [Initial]
  ✅ Herz: Klappe mit CABG (ID: 2237) [Initial]
  ✅ Transplantation: Herz/Lunge (ID: 2270) [Initial]

In [15]:
items_id_list

[2208,
 2240,
 2241,
 707,
 708,
 2272,
 2274,
 744,
 2280,
 2282,
 719,
 2227,
 724,
 3096,
 2237,
 2270]

In [16]:
discharge_data_preprocess.d_references_data[discharge_data_preprocess.d_references_data['ReferenceUnit'] == '/min']

,ReferenceGlobalID,ReferenceValue,ReferenceName,ReferenceDescription,ReferenceUnit,ReferenceOrder,ReferenceType,Data,LOINC_code,LOINC_short,LOINC_long
546,707,HeartRateECG,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
547,708,HeartRateSPO2,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
558,719,RespRate,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
563,724,HeartRateABP,SignalFloat,NaN,/min,0,0.0,NaN,NaN,NaN,NaN
1485,2274,RespRateEKG,SignalFloat,NaN,/min,0,NaN,NaN,NaN,NaN,NaN
1491,2280,RespRateSpontanous,SignalFloat,NaN,/min,0,NaN,NaN,NaN,NaN,NaN
1493,2282,RespRate,RespiratorSetting,NaN,/min,0,NaN,NaN,NaN,NaN,NaN